apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-cfg
data:
  jupyterhub_config.py: |
    # Installera CAS-modulen

    import sys, subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'jhub_cas_authenticator'])

    # Konfigurera CAS

    CAS_BASE_URL = 'https://idp3.it.gu.se/idp/profile/cas'
    c.CASAuthenticator.cas_login_url = '%s/login' % CAS_BASE_URL
    c.CASAuthenticator.cas_logout_url = '%s/logout' % CAS_BASE_URL
    c.CASAuthenticator.cas_service_validate_url = '%s/serviceValidate' % CAS_BASE_URL
    c.CASAuthenticator.cas_service_url = 'https://%s/login' % host
    c.JupyterHub.authenticator_class = 'jhub_cas_authenticator.cas_auth.CASAuthenticator'

    # Tillåt inga oregistrerade användare att logga in. Kräver att
    # minst en administratör har angivits i fältet jupyterhub_admins i
    # ConfigMap:en jupyterhub-cfg. En tom lista innebär att vem som
    # helst får logga in.

    if admin_users:
      c.Authenticator.whitelist = set(admin_users.split(','))

    # Ta bort formuläret som visas när en notebook skapas

    delattr(OpenShiftSpawner, '_options_form_default')
    delattr(KubeSpawner, '_options_form_default')

    # Hårdkoda image

    c.KubeSpawner.image_spec = 's2i-minimal-notebook:v0.0.4'

    # Öppna Jupyter Lab isf filträdet

    c.KubeSpawner.default_url = '/lab'

    # Montera delad volym skrivskyddad för vanliga användare, och
    # skrivbar för administratörer

    def _gu_custom_pre_spawn_hook(spawner):
      setup_environment(spawner)
      readOnly = not spawner.user.admin
      spawner.volumes.append({
        'name': 'shared',
        'persistentVolumeClaim': {
          'claimName': '%s-shared' % os.environ['JUPYTERHUB_SERVICE_NAME'],
          'readOnly': readOnly
        }
      })
      spawner.volume_mounts.append({
        'name': 'shared',
        'mountPath': '/opt/app-root/src/shared'
      })

    c.OpenShiftSpawner.pre_spawn_hook = _gu_custom_pre_spawn_hook

  jupyterhub_admins: ""
  gpu_mode: ""
  singleuser_pvc_size: 2Gi
